site_name: Les notes de Yuri

theme: 
  name: 'material'
  palette:
    scheme: slate
    primary: orange
    accent: yellow
    language: fr
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.code.copy
  font:
    text: Gabarito
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite